import type { Metadata } from "next";
import { Martian_Mono } from "next/font/google";
import "./globals.css";


const font = Martian_Mono({
  subsets: ['latin'],
  weight: ['100','200','300','400','500','600','700','800'],
});

export const metadata: Metadata = {
  title: "Tuna Online Compiler",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
  <html lang="en" className="h-full bg-white">
    <body className={`${font.className} min-h-full flex flex-col antialiased`}>
      {children}
    </body>
  </html>
  );
}
